services:
    gospodinenotik.advancedhide.parser:
        class: gospodinenotik\advancedhide\service\block_parser
        arguments:
            - '@config'
            - '%core.root_path%'
            - '%core.php_ext%'

    gospodinenotik.advancedhide.auth_service:
        class: gospodinenotik\advancedhide\service\auth_service
        arguments:
            - '@config'
            - '@user'
            - '@auth'
            - '@dbal.conn'
            - '@dbal.tools'
            - '@language'
            - '@cache.driver'
            - '%core.table_prefix%'
            - '@captcha.factory'
            - '%core.root_path%'
            - '%core.php_ext%'

    gospodinenotik.advancedhide.listener:
        class: gospodinenotik\advancedhide\event\main_listener
        arguments:
            - '@config'
            - '@user'
            - '@auth'
            - '@template'
            - '@request'
            - '@language'
            - '@dbal.conn'
            - '@gospodinenotik.advancedhide.parser'
            - '@gospodinenotik.advancedhide.auth_service'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    gospodinenotik.advancedhide.controller:
        class: gospodinenotik\advancedhide\controller\main_controller
        arguments:
            - '@config'
            - '@user'
            - '@auth'
            - '@dbal.conn'
            - '@request'
            - '@language'
            - '@cache.driver'
            - '@gospodinenotik.advancedhide.parser'
            - '@gospodinenotik.advancedhide.auth_service'
            - '@captcha.factory'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'

    gospodinenotik.advancedhide.console.reparse:
        class: gospodinenotik\advancedhide\console\command\reparse
        arguments:
            - '@user'
            - '@dbal.conn'
            - '@gospodinenotik.advancedhide.parser'
            - '%core.table_prefix%'
        tags:
            - { name: console.command }

    gospodinenotik.advancedhide.cron.tidy_logs:
        class: gospodinenotik\advancedhide\cron\tidy_logs
        arguments:
            - '@config'
            - '@dbal.conn'
            - '%core.table_prefix%'
        calls:
            - [set_name, [gospodinenotik.advancedhide.cron.tidy_logs]]
        tags:
            - { name: cron.task }